package models

import (
	"time"
)

// Role represents a user role in the system.
type Role struct {
	ID          string    `json:"id"`          // Unique identifier for the role (UUID)
	Name        string    `json:"name"`        // Name of the role (e.g., "admin", "user")
	Description string    `json:"description"` // Description of the role
	CreatedAt   time.Time `json:"created_at"`  // Timestamp when the role was created
	UpdatedAt   time.Time `json:"updated_at"`  // Timestamp when the role was last updated
}

// NewRole creates a new Role instance with default creation/update timestamps.
// The ID should be generated by the database/service.
func NewRole(name, description string) *Role {
	now := time.Now()
	return &Role{
		ID:          "", // ID should be generated by the database/service
		Name:        name,
		Description: description,
		CreatedAt:   now,
		UpdatedAt:   now,
	}
}
